LemonadeStand.Web/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using LemonadeStand.Common;
using LemonadeStand.Common.Commands;
using LemonadeStand.Common.Persistence;

namespace LemonadeStand.Web.Controllers
{
    public class 
        GameController : Controller
    {
        private GameApplicationRepository repo;

        public GameController()
        {
            repo = new GameApplicationRepository();
        }

        //
        // GET: /Game/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateGame(CreateGame createGame)
        {
            var cmd = new CreateGameCommand(repo);
            var result = cmd.Execute(createGame);
            return Json(result);
        }

        public ActionResult NextDay(GameId gameId)
        {
            var cmd = new NextDayCommand(repo);
            var result = cmd.Execute(gameId);
            return Json(result);
        }

        public ActionResult FinishDay(AddChoices addChoices)
        {
            var addChoicesCommand = new AddChoicesCommand(repo);
            var finishDayCommand = new FinishDayCommand(repo);

            addChoicesCommand.Execute(addChoices);
            var result = finishDayCommand.Execute(addChoices);
            
            return Json(result);
        }

        public ActionResult Urls()
        {
            return Json(new
            {
                views = new
                {
                    createGame = Url.Action("CreateGame", "GameViews"),
                    welcome = Url.Action("Welcome", "GameViews"),
                    weatherForecast = Url.Action("WeatherForecast", "GameViews"),
                    input = Url.Action("Input", "GameViews"),
                    financialReport = Url.Action("FinancialReport", "GameViews")
                },
                actions = new 
                {
                    createGame = Url.Action("CreateGame"),
                    nextDay = Url.Action("NextDay"),
                    finishDay = Url.Action("FinishDay")
                }
            }, JsonRequestBehavior.AllowGet);
        }
    }

    public class GameApplicationRepository : IRepository<Game>
    {
        private static readonly object LockObj = new object();
        private static readonly List<Game> Items = new List<Game>();

        public void Insert(Game entity)
        {
            lock (LockObj)
            {
                Items.Add(entity);
            }
        }

        public void Delete(Game entity)
        {
            lock (LockObj)
            {
                Items.Remove(entity);
            }
        }

        public IQueryable<Game> Query()
        {
            return Items.AsQueryable();
        }

        public Game Get(Expression<Func<Game, bool>> predicate)
        {
            return Query().FirstOrDefault(predicate);
        }
    }
}

LemonadeStand.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace LemonadeStand.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string id)
        {
            ViewBag.OgDescription = id;
            return View();
        }
    }
}

LemonadeStand.Web/Views/Home/Index.cshtml
<div class="jumbotron">
    <img src="@Url.Content("~/Content/Images/glass.png")" class="pull-right hidden-xs"/>
    <h1>Lemonade Stand</h1>
    <p class="lead">
        A family-friendly business simulation game for up to 30 local players.<br/>
        Manage a lemonade stand on your street with money you got from your mom.
    </p>
    <div class="text-center">
        <a href="@Url.Action("Index", "Game")" class="btn btn-info btn-lg">Play the game</a>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        Hi! Welcome to Lemonsville, California!
    </div>
    <div class="panel-body">
        <p>
            In this small town, you are in charge of running your own lemonade stand.<br />
            You can compete with as many other people as you wish, but how much profit you make is up to you
            (the other stands' sales will not affect your business in any way).<br />
            If you make the most money, you're the winner!!
        </p>
        <p>
            To manage your lemonade stand, you will  need to make these decisions every day:
            <ol>
                <li>How many glasses of lemonade to make (only one batch is made each morning)</li>
                <li>How many advertising signs to make (the signs cost fifteen cents each)</li>
                <li>What price to charge for each glass</li>
            </ol>
        </p>
        <p>
            You will begin with $2.00 cash (assets).<br />
            Because your mother gave you some sugar, your cost to make lemonade is two cents per glass (this may change in the future).<br />
            Your expenses are the sum of the cost of the lemonade and the cost of the signs.<br />
            Your profits are the difference between the income from sales and your expenses.<br />
            The number of glasses you sell each day depends on the price you charge, and on the number of advertising signs you use.<br />
            Keep track of your assets, because you can't spend more money than you have!
        </p>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        What's technical?
    </div>
    <div class="panel-body">
        <p>
            A C# port of the original 1973 game by Bob Jamison of the MECC,
            greatly helped by the port by Codenautics of the 1979 Apple II game.
            See
            <a href="http://codenautics.com/lemonade/" target="_blank">Codenautics Lemonade Stand remake</a> and
            <a href="http://en.wikipedia.org/wiki/Lemonade_Stand" target="_blank">Wikipedia</a>.
        </p>
        <p>
            The code is available at <a href="https://github.com/lars-erik/lemonade-stand" target="_blank">GitHub</a>.</p>
    </div>
</div>

<div class="text-center">
    <a href="@Url.Action("Index", "Game")" class="btn btn-default btn-lg">Play the game</a>
</div>